version: '3.2'
services:
  postgres:
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      - "POSTGRES_USER=test"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=mytest"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    build: './database'
    networks:
      infranet:
        aliases:
          - 'postgres'

networks:
  infranet:
