version: 2
jobs:
  build:
    working_directory: ~/cci-film-ratings # directory where steps will run
    docker:
      - image: chrishowejones/cci-clojure:lein-2.8.1
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m # limit the maximum heap size to prevent out of memory errors
    steps:
      - checkout
      - restore_cache:
          key: film-ratings-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: film-ratings-{{ checksum "project.clj" }}
      - run: lein do test2junit, cloverage -o cloverage
      - store_test_results: # upload test results
          path: test2junit/xml
      - store_artifacts: # upload html test report
          path: test2junit/html
          destination: test-report
      - store_artifacts: # upload cloverage report
          path: cloverage
          destination: cloverage-report
      - run: lein uberjar
      - store_artifacts: # upload jar to Artifacts
          path: target/film-ratings.jar
          destination: uberjar
